services:
  - type: web
    name: minha-app
    env: python
    plan: free
    region: oregon
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
